name: 

variables:
  NG_CACHE_DIR_PATH: '.angular/cache'

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseNode@1
    displayName: Install Node.js
    inputs:
      version: 16

  - task: Npm@1
    displayName: Install NPM Dependencies
    inputs:
      command: install

  - task: Cache@2
    displayName: Use Angular CLI Build Cache
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      path: $(NG_CACHE_DIR_PATH)

  - task: Npm@1
    displayName: Build Angular App
    inputs:
      command: custom
      customCommand: 'run build -- --configuration=production --output-path=$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'